### ISSUE TITLE
The key pair 'image-builder-kp' does not exist

### ISSUE THREAD

**Issue by maurosisa** [masterwali/ec2-image-builder#1]
Hello @masterwali 

After having configured inputs.yaml , launching the terragrunt plan command , I get the following errors 
`Terraform has been successfully initialized!
╷
│ Error: no matching subnet found
│ 
│   with data.aws_subnet.this,
│   on main.tf line 14, in data "aws_subnet" "this":
│   14: data "aws_subnet" "this" {
│ 
╵
╷
│ Error: no matching SecurityGroup found
│ 
│   with data.aws_security_group.this,
│   on main.tf line 21, in data "aws_security_group" "this":
│   21: data "aws_security_group" "this" {
│ 
╵
ERRO[0004] 1 error occurred:
	* exit status 1
`

Could you please help me to resolve the issue ?
Thanks a lot in advance
mau

**Comment by maurosisa** [comment]
Hello @masterwali 

I managed to resolve that errors configuring tags in my subnet and SecurityGroup resources and the terragrunt plan completes successfully.
But in the apply phase I get the following error 

   │ Error: error waiting for Image Builder Image (arn:aws:imagebuilder:eu-south-1:accountid:image/amazon-linux-recipe/1.0.0/1) to become available: The key pair 'image-builder-kp' does not exist
│ 
│   with aws_imagebuilder_image.this,
│   on 1-recipe.tf line 1, in resource "aws_imagebuilder_

Please for your help,
Best Regards
mau

**Comment by waleed0402** [comment]
That sounds like the IAM role or user account doesn’t have the correct KMS key policy. Take a look at how I create KMS keys; https://cloudly.engineer/2020/aws-kms-customer-managed-cmk-with-terraform/aws/ or look at AWS original docs.

**Comment by maurosisa** [comment]
Hello @masterwali Thank you very much !
I created the key from the console without adding the related roles 

role/aws-service-role/support.amazonaws.com/AWSServiceRoleForSupport",
ole/aws-service-role/trustedadvisor.amazonaws.com AWSServiceRoleForTrustedAdvisor


I would implement the key also with Terragrunt, but I cannot understand the structure that you give to the folders , but I understand that it is the "multiaccount" version of this one
with Terraform [https://www.bogotobogo.com/DevOps/Terraform/Terraform-AWS-KMS.php](url).
Also the module @cloudly-engineer/aws/tf-modules/kms.git doesn't exist anymore.
It would be great if you could implement also that tutorial with a github repo ! 
Thanks a lot
mau

**Comment by waleed0402** [comment]
@maurosisa here's my KMS module https://github.com/masterwali/terraform-aws-kms-module
