### ISSUE TITLE
Versioning components and recipes

### ISSUE THREAD

**Issue by evilensky** [masterwali/ec2-image-builder#2]
Thank you kindly for this code and the blog post!

Do you have any guidance on the correct way to version (increment) component versions and recipe versions?

We are finding that manually increment a recipe version causes tf to attempt to destroy the previous recipe version, which appears to be an invalid operation because there is still a dependent component?

**Comment by waleed0402** [comment]
Yes. I need to add _create_before_destroy_ on the recipe resource. I'll work it when I get time. Feel free to contribute.

**Comment by waleed0402** [comment]
@evilensky Fix released!
